#%RAML 1.0
title: currency_exchange
version: v0
baseUri: http://api.demo-currency-exchange.com


uses:
  financialObjects: types/financialObjects.raml
  pagination: types/pagination.raml
  annotations: ./annotations/annotationsLibrary.raml

annotationTypes:
  countrySpecific: !include annotations/countrySpecific.raml
  enumDescription: !include annotations/enumDescription.raml

traits:
  sortable: !include traits/sortable.raml
  pageable: !include traits/pageable.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml
  subresource-collection: !include resourceTypes/subresource-collection.raml

types:
  errors: !include types/errors.raml


/currency-exchange:
  description: |
    Api demo curso RAML.
  type: collection
  /financial-object:
    post:
      description: Create a new resource.
      body:
        application/json:
          type: financialObjects.financialObjects
          examples: !include examples/financial-object/post_resquest.json
      responses:
        201:
          description: |
            Succesfully created a new resource
          headers:
            Location:
              description: |
                Location of the newly created resource
          body:
            application/json:
              type: financialObjects.financialObjects #aqui se necesita especificar que se da de salida en el 201, se puede colocar el type como file o explcito anonimo
              examples:

        400:
          description: |
            Bad Request.
          body:
            application/json:
              type: errors
              examples:
                AliasDelError:
                  value: !include examples/financial-object/post_400.json
                  displayName: Nombre del error.
                  description: Descripcion del error.
    get:
      description: Lista los tipos de cambio # aqui se necesita terminar la implenetacion del get
      type: collection
      responses:
        200:
          description: Lista las tasas de conversion
          body:
            application/json:
              type: financialObjects.financialObjects[]
              examples: !include examples/financial-object/get_200.json
