#%RAML 1.0
title: currency_exchange
version: v0
baseUri: http://api.demo-currency-exchange.com


uses:
  #financialObjects: types/financialObjects.raml
  pagination: types/pagination.raml
  annotations: annotations/annotationsLibrary.raml

annotationTypes:
  countrySpecific: !include annotations/countrySpecific.raml
  enumDescription: !include annotations/enumDescription.raml

traits:
  sortable: !include traits/sortable.raml
  pageable: !include traits/pageable.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml
  subresource-collection: !include resourceTypes/subresource-collection.raml

types:
  errors: !include types/errors.raml

types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number

/currency-exchange:
  description: |
    Api demo curso RAML.
  /financial-object:
    post:
      description: Create a new resource.
      body:
        application/json:
            type: object
            description: Description del type
            properties:
              type:
                (annotations.bindingDefinition):
                  - method: "POST"
                    input: "REQUIRED"
                    output: "REQUIRED"
                enum: [Foreing_exchange, Foreing_exchange_Digital]
                (annotations.enumDescription):
                  - Foreing_exchange: Tipo para tasa de cambio para monedas físicas.
                  - Foreing_exchange_Digital: Tipo para tasa de cambio para monedas virtuales.
                description: : Type of foreign exchange
                required: false
              name:
                type: String
                description: Name of foreign exchange
                required: false
              shortName:
                type: String
                description: Short name of the foreign exchange
                required: false
              rates:
                type: object
                description: Rate between the currencies.
                items:
                  properties:
                    id:
                      type: number
                      description: Identifier of the rate
                    value:
                      type: number
                      descriptio: Value of the rate
            examples: !include examples/financial-object/post_resquest.json
      responses:
        204:
          description: |
            No Content.
        400:
          description: |
            Bad Request.
          body:
            application/json:
              type: errors
              examples:
                AliasDelError:
                  value: !include examples/financial-object/post_400.json
                  displayName: Nombre del error.
                  description: Descripcion del error.
    get:
      description: Lista los tipos de cambio
      responses:
        201:
          description: |
            Succesfully created a new resource
          headers:
            Location:
              description: |
                Location of the newly created resource
              type: object
              required: false
