#%RAML 1.0 Library

uses:
  annotations: ../annotations/annotationsLibrary.raml

types:
  fromCurrency:
    type: object
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "REQUIRED"
            output: "NONE"
        type: number
        required: false
        description: Identifier of currency
      name:
        (annotations.bindingDefinition):
          - method: "POST"
            input: "REQUIRED"
            output: "NONE"
        type: string
        required: false
        description: Name of the currency
