#%RAML 1.0 Library
uses:
  annotations: ../annotations/annotationsLibrary.raml
types:
  pagination:
    type: object
    properties:
      links:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
        type: object
        required: false
        description: |
          Pagination links. These links provide relative URIs to reach different useful pages, such as first, last, next or previous pages.
        properties:
          first:
            (annotations.bindingDefinition):
              - method: "GET"
                input: "NONE"
                output: "REQUIRED"
              - method: "POST"
                input: "NONE"
                output: "REQUIRED"
            type: string
            required: false
            description: |
              URI to the first page. It will be the URI to the list without paging element.

          last:
            (annotations.bindingDefinition):
              - method: "GET"
                input: "NONE"
                output: "OPTIONAL"
              - method: "POST"
                input: "NONE"
                output: "OPTIONAL"
            type: string
            required: false
            description: |
              URI to the last page based on the current pagination configuration.
          previous:
            (annotations.bindingDefinition):
              - method: "GET"
                input: "NONE"
                output: "OPTIONAL"
              - method: "POST"
                input: "NONE"
                output: "OPTIONAL"
            type: string
            required: false
            description: |
              URI to the previous page.

          next:
            (annotations.bindingDefinition):
              - method: "GET"
                input: "NONE"
                output: "OPTIONAL"
              - method: "POST"
                input: "NONE"
                output: "OPTIONAL"
            type: string
            required: false
            description: |
              URI to the next page.
      page:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: number
        required: false
        description: |
          Current page number. This attribue value is 0 when referring to the first page.
      totalPages:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: number
        required: false
        description: |
          Total number of pages for the provided pagination and filtering parameters.
      totalElements:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: number
        required: false
        description: |
          Total number of items to the requested list, taking into account possible filtering criteria if specified.

      pageSize:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "NONE"
            output: "OPTIONAL"
          - method: "POST"
            input: "NONE"
            output: "OPTIONAL"
        type: number
        required: false
        description: |
          Number of items per page. This attribute value matches pageSize query parameter if provided. Otherwise, this attribute may provide the default page size.
