#%RAML 1.0 Library
annotationTypes:
  countrySpecific: !include countrySpecific.raml
  exampleInput: !include exampleInput.raml
  bindingDefinition: !include bindingDefinition.raml
  bindingView: !include bindingView.raml
  enumDescription: !include enumDescription.raml
  functionalError: !include functionalError.raml
  countryException: !include countryException.raml
  serviceId: !include serviceId.raml
  virtualService: !include virtualService.raml
