#%RAML 1.0 Trait
queryParameters:
  pageSize:
    description: Number of elements per page
    type: integer
    required: false
    example: 20
  paginationKey:
    description: Key to obtain a single page
    type: string
    required: false
    example: facb4747f
